import React from 'react'
import '../Footer/footer.css'
import swiggyFooter from '../../Images/swiggyFooter.png'

const Footer = () => {
  return (
    <div className='footer'>
        <div className='innerFooter'>
        <div className='list1'>
            <ul style={{listStyle: 'none',color: 'white'}}>
                <li><b>COMPANY</b></li>
                <li>About Us</li>
                <li>Team</li>
                <li>Careers</li>
                <li>Swiggy Blog</li>
                <li>Bug Bounty</li>
                <li>Swiggy One</li>
                <li>Swiggy Corporate</li>
                <li>Swiggy Instamart</li>
                <li>Swiggy Genie</li>
            </ul>
        </div>
        <div className='list2'>
            <ul style={{listStyle: 'none',color: 'white'}}>
                <li><b>CONTACT</b></li>
                <li>Help & Support</li>
                <li>Partner with Us</li>
                <li>Ride with us</li>
            </ul>
        </div>
        <div className='list3'>
            <ul style={{listStyle: 'none',color: 'white'}}>
                <li><b>LEGAL</b></li>
                <li>Terms & Conditions</li>
                <li>Refund & Cancellation</li>
                <li>Privacy Policy</li>
                <li>Cookie Policy</li>
                <li>Offer Terms</li>
                <li>Phising & Fraud</li>
            </ul>
        </div>
        <div className='google-footer'>
            <img src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,h_108/play_ip0jfp" alt="" className='googleFooter1' />
            <img src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,h_108/iOS_ajgrty" alt="" className='googleFooter2' />
        </div>
        </div>
        <div style={{ borderBottom: '1px solid grey',width:'95vw',marginLeft:'3%',marginTop: '3%',}}></div>
        <div className='citiList'>
        <div className='list4'>
            <ul style={{listStyle: 'none',color: 'white'}}>
                <li><b>WE DELIVER TO</b></li>
                <li>Abohar</li>
                <li>Adilabad</li>
                <li>Adityapur</li>
                <li>Adoni</li>
                <li>Agartala</li>
                <li>Agra</li>
                <li>Ahmedabad</li>
                <li>Ahmednagar</li>
                <li>Aizawl</li>
                <li>Ajmer</li>
                <li>Akola</li>
                <li>Alappuzha</li>
                <li>Aligar</li>
                <li>Alipurduar</li>
                <li>Allahabad</li>
                <li>Almora</li>
                <li>Alwar</li>
                <li>Ambajogai</li>
                <li>Ambala</li>
                <li>Ambikapur</li>
                <li>Ambur</li>
                <li>Amravati</li>
                <li>Amreli</li>
                <li>Amritsar</li>
                <li>Anand</li>
                <li>Anantapur</li>
                <li>Ankleshwar</li>
                <li>Arakkonam</li>
                <li>Arambagh</li>
                <li>Araria</li>
                <li>Arrah</li>
                <li>Asansol</li>
                <li>Aurangabad</li>
                <li>Aurangabadbihar</li>
                <li>Azamgarh</li>
                <li>Baddi</li>
                <li>Bagalkot</li>
                <li>Bagdogra</li>
                <li>Bahadurgarh</li>
                <li>Bahraich</li>
                <li>Balaghat</li>
                <li>Balangir</li>
                <li>Balasore</li>
                <li>Ballari</li>
                <li>Ballia</li>
                <li>Balrampur</li>
                <li>Balurghat</li>
                <li>Banda</li>
                <li>Banglore</li>
                <li>Bankura</li>
                <li>Baramati</li>
                <li>Baran</li>
                <li>Bardhaman</li>
                <li>Bardoli</li>
                <li>Bareliy</li>
                <li>Barh</li>
                <li>Baripada</li>
                <li>Barmer</li>
                <li>Barnala</li>
                <li>Barshi</li>
                <li>Basirhat</li>
                <li>Basti</li>
                <li>Batala</li>
                <li>Bathinda</li>
                <li>Beawar</li>
                <li>Beed</li>
                <li>Begusarai</li>
                <li>Pratapgarh</li>
                <li>Belgaum</li>
                <li>Berhampore</li>
                <li>Berhampur</li>
                <li>Bettiah</li>
                <li>Betul</li>
                <li>Bhadohi</li>
                <li>Bhadrachalam</li>
                <li>Bhadrak</li>
                <li>Bhadravati</li>
                <li>Bhagalpur</li>
                <li>Bhandara</li>
                <li>Bharabanki</li>
                <li>Bharatpur</li>
                <li>Bharuch</li>
                <li>Bhatkal</li>
                <li>Bhavnagar</li>
                <li>Bhawanipatna</li>
                <li>Bhilai</li>
                <li>Bhilwara</li>
                <li>Bhimavaram</li>
                <li>Bhind</li>
                <li>Bhiwadi</li>
                <li>Bhiwani</li>
                <li>Bhopal</li>
                <li>Bhuanewsar</li>
                <li>Bhuj</li>
                <li>Bhusaval</li>
                <li>Bidar</li>
                <li>Biharsarif</li>
                <li>Bijapur</li>
                <li>Bijnor</li>
                <li>Bikaner</li>
                <li>Bilaspur</li>
                <li>Bilimora</li>
                <li>Biswanath-Chariali</li>
                <li>Bodhan-Rural</li>
                <li>Bodinayakanur</li>
                <li>Boisar</li>
                <li>Bokaro</li>
                <li>Bolpur</li>
                <li>Bongaigaon</li>
                <li>Bongaon</li>
                <li>Budaun</li>
                <li>Budhwal</li>
                <li>Bulandshahr</li>
                <li>Buldhan</li>
                <li>Bundi</li>
                <li>Burhanpur</li>
                <li>Buxar</li>
                <li>Central-Goa</li>
                <li>Chaibasa</li>
                <li>Chakdaha</li>
                <li>Chalisgaon</li>
                <li>Chandausi</li>
                <li>Chandigarh</li>
                <li>Chandrapur</li>
                <li>Chennai</li>
                <li>Chhapra</li>
                <li>Chhatarpur</li>
                <li>Chhindwara</li>
                <li>Chidambaram</li>
                <li>Chikhli</li>
                <li>Chikkaballapur</li>
                <li>Chikmanglur</li>
                <li>Chiplun</li>
                <li>Chitradurga</li>
                <li>Chittoor</li>
                <li>Chittorgarh</li>
                <li>Churu</li>
                <li>Coimbator</li>
                <li>Cooch-Behar</li>
                <li>Cuddalore</li>
                <li>Cuttack</li>
                <li>Dahanu</li>
                <li>Dahod</li>
                <li>Daltonganj</li>
                <li>Daman</li>
                <li>Darbhanga</li>
                <li>Darjeeling</li>
                <li>Dasuya</li>
                <li>Dausa</li>
                <li>Davanagere</li>
            </ul>
        </div>
        <div className='list5'>
            <ul style={{listStyle: 'none',color: 'white'}}>
                <li>Dehradun</li>
                <li>Adityapur</li>
                <li>Adoni</li>
                <li>Agartala</li>
                <li>Agra</li>
                <li>Ahmedabad</li>
                <li>Ahmednagar</li>
                <li>Aizawl</li>
                <li>Ajmer</li>
                <li>Akola</li>
                <li>Alappuzha</li>
                <li>Aligar</li>
                <li>Alipurduar</li>
                <li>Allahabad</li>
                <li>Almora</li>
                <li>Alwar</li>
                <li>Ambajogai</li>
                <li>Ambala</li>
                <li>Ambikapur</li>
                <li>Ambur</li>
                <li>Amravati</li>
                <li>Amreli</li>
                <li>Amritsar</li>
                <li>Anand</li>
                <li>Anantapur</li>
                <li>Ankleshwar</li>
                <li>Arakkonam</li>
                <li>Arambagh</li>
                <li>Araria</li>
                <li>Arrah</li>
                <li>Asansol</li>
                <li>Aurangabad</li>
                <li>Aurangabadbihar</li>
                <li>Azamgarh</li>
                <li>Baddi</li>
                <li>Bagalkot</li>
                <li>Bagdogra</li>
                <li>Bahadurgarh</li>
                <li>Bahraich</li>
                <li>Balaghat</li>
                <li>Balangir</li>
                <li>Balasore</li>
                <li>Ballari</li>
                <li>Ballia</li>
                <li>Balrampur</li>
                <li>Balurghat</li>
                <li>Banda</li>
                <li>Banglore</li>
                <li>Bankura</li>
                <li>Baramati</li>
                <li>Baran</li>
                <li>Bardhaman</li>
                <li>Bardoli</li>
                <li>Bareliy</li>
                <li>Barh</li>
                <li>Baripada</li>
                <li>Barmer</li>
                <li>Barnala</li>
                <li>Barshi</li>
                <li>Basirhat</li>
                <li>Basti</li>
                <li>Batala</li>
                <li>Bathinda</li>
                <li>Beawar</li>
                <li>Beed</li>
                <li>Begusarai</li>
                <li>Pratapgarh</li>
                <li>Belgaum</li>
                <li>Berhampore</li>
                <li>Berhampur</li>
                <li>Bettiah</li>
                <li>Betul</li>
                <li>Bhadohi</li>
                <li>Bhadrachalam</li>
                <li>Bhadrak</li>
                <li>Bhadravati</li>
                <li>Bhagalpur</li>
                <li>Bhandara</li>
                <li>Bharabanki</li>
                <li>Bharatpur</li>
                <li>Bharuch</li>
                <li>Bhatkal</li>
                <li>Bhavnagar</li>
                <li>Bhawanipatna</li>
                <li>Bhilai</li>
                <li>Bhilwara</li>
                <li>Bhimavaram</li>
                <li>Bhind</li>
                <li>Bhiwadi</li>
                <li>Bhiwani</li>
                <li>Bhopal</li>
                <li>Bhuanewsar</li>
                <li>Bhuj</li>
                <li>Bhusaval</li>
                <li>Bidar</li>
                <li>Biharsarif</li>
                <li>Bijapur</li>
                <li>Bijnor</li>
                <li>Bikaner</li>
                <li>Bilaspur</li>
                <li>Bilimora</li>
                <li>Biswanath-Chariali</li>
                <li>Bodhan-Rural</li>
                <li>Bodinayakanur</li>
                <li>Boisar</li>
                <li>Bokaro</li>
                <li>Bolpur</li>
                <li>Bongaigaon</li>
                <li>Bongaon</li>
                <li>Budaun</li>
                <li>Budhwal</li>
                <li>Bulandshahr</li>
                <li>Buldhan</li>
                <li>Bundi</li>
                <li>Burhanpur</li>
                <li>Buxar</li>
                <li>Central-Goa</li>
                <li>Chaibasa</li>
                <li>Chakdaha</li>
                <li>Chalisgaon</li>
                <li>Chandausi</li>
                <li>Chandigarh</li>
                <li>Chandrapur</li>
                <li>Chennai</li>
                <li>Chhapra</li>
                <li>Chhatarpur</li>
                <li>Chhindwara</li>
                <li>Chidambaram</li>
                <li>Chikhli</li>
                <li>Chikkaballapur</li>
                <li>Chikmanglur</li>
                <li>Chiplun</li>
                <li>Chitradurga</li>
                <li>Chittoor</li>
                <li>Chittorgarh</li>
                <li>Churu</li>
                <li>Coimbator</li>
                <li>Cooch-Behar</li>
                <li>Cuddalore</li>
                <li>Cuttack</li>
                <li>Dahanu</li>
                <li>Dahod</li>
                <li>Daltonganj</li>
                <li>Daman</li>
                <li>Darbhanga</li>
                <li>Darjeeling</li>
                <li>Dasuya</li>
                <li>Dausa</li>
                <li>Davanagere</li>
                <li>Hajipur</li>
            </ul>
        </div>
        <div className="list6">
            <ul style={{listStyle: 'none',color: 'white'}}>
                <li>Kharagpur</li>
                <li>Adityapur</li>
                <li>Adoni</li>
                <li>Agartala</li>
                <li>Agra</li>
                <li>Ahmedabad</li>
                <li>Ahmednagar</li>
                <li>Aizawl</li>
                <li>Ajmer</li>
                <li>Akola</li>
                <li>Alappuzha</li>
                <li>Aligar</li>
                <li>Alipurduar</li>
                <li>Allahabad</li>
                <li>Almora</li>
                <li>Alwar</li>
                <li>Ambajogai</li>
                <li>Ambala</li>
                <li>Ambikapur</li>
                <li>Ambur</li>
                <li>Amravati</li>
                <li>Amreli</li>
                <li>Amritsar</li>
                <li>Anand</li>
                <li>Anantapur</li>
                <li>Ankleshwar</li>
                <li>Arakkonam</li>
                <li>Arambagh</li>
                <li>Araria</li>
                <li>Arrah</li>
                <li>Asansol</li>
                <li>Aurangabad</li>
                <li>Aurangabadbihar</li>
                <li>Azamgarh</li>
                <li>Baddi</li>
                <li>Bagalkot</li>
                <li>Bagdogra</li>
                <li>Bahadurgarh</li>
                <li>Bahraich</li>
                <li>Balaghat</li>
                <li>Balangir</li>
                <li>Balasore</li>
                <li>Ballari</li>
                <li>Ballia</li>
                <li>Balrampur</li>
                <li>Balurghat</li>
                <li>Banda</li>
                <li>Banglore</li>
                <li>Bankura</li>
                <li>Baramati</li>
                <li>Baran</li>
                <li>Bardhaman</li>
                <li>Bardoli</li>
                <li>Bareliy</li>
                <li>Barh</li>
                <li>Baripada</li>
                <li>Barmer</li>
                <li>Barnala</li>
                <li>Barshi</li>
                <li>Basirhat</li>
                <li>Basti</li>
                <li>Batala</li>
                <li>Bathinda</li>
                <li>Beawar</li>
                <li>Beed</li>
                <li>Begusarai</li>
                <li>Pratapgarh</li>
                <li>Belgaum</li>
                <li>Berhampore</li>
                <li>Berhampur</li>
                <li>Bettiah</li>
                <li>Betul</li>
                <li>Bhadohi</li>
                <li>Bhadrachalam</li>
                <li>Bhadrak</li>
                <li>Bhadravati</li>
                <li>Bhagalpur</li>
                <li>Bhandara</li>
                <li>Bharabanki</li>
                <li>Bharatpur</li>
                <li>Bharuch</li>
                <li>Bhatkal</li>
                <li>Bhavnagar</li>
                <li>Bhawanipatna</li>
                <li>Bhilai</li>
                <li>Bhilwara</li>
                <li>Bhimavaram</li>
                <li>Bhind</li>
                <li>Bhiwadi</li>
                <li>Bhiwani</li>
                <li>Bhopal</li>
                <li>Bhuanewsar</li>
                <li>Bhuj</li>
                <li>Bhusaval</li>
                <li>Bidar</li>
                <li>Biharsarif</li>
                <li>Bijapur</li>
                <li>Bijnor</li>
                <li>Bikaner</li>
                <li>Bilaspur</li>
                <li>Bilimora</li>
                <li>Biswanath-Chariali</li>
                <li>Bodhan-Rural</li>
                <li>Bodinayakanur</li>
                <li>Boisar</li>
                <li>Bokaro</li>
                <li>Bolpur</li>
                <li>Bongaigaon</li>
                <li>Bongaon</li>
                <li>Budaun</li>
                <li>Budhwal</li>
                <li>Bulandshahr</li>
                <li>Buldhan</li>
                <li>Bundi</li>
                <li>Burhanpur</li>
                <li>Buxar</li>
                <li>Central-Goa</li>
                <li>Chaibasa</li>
                <li>Chakdaha</li>
                <li>Chalisgaon</li>
                <li>Chandausi</li>
                <li>Chandigarh</li>
                <li>Chandrapur</li>
                <li>Chennai</li>
                <li>Chhapra</li>
                <li>Chhatarpur</li>
                <li>Chhindwara</li>
                <li>Chidambaram</li>
                <li>Chikhli</li>
                <li>Chikkaballapur</li>
                <li>Chikmanglur</li>
                <li>Chiplun</li>
                <li>Chitradurga</li>
                <li>Chittoor</li>
                <li>Chittorgarh</li>
                <li>Churu</li>
                <li>Coimbator</li>
                <li>Cooch-Behar</li>
                <li>Cuddalore</li>
                <li>Cuttack</li>
                <li>Dahanu</li>
                <li>Dahod</li>
                <li>Daltonganj</li>
                <li>Daman</li>
                <li>Darbhanga</li>
                <li>Darjeeling</li>
                <li>Dasuya</li>
                <li>Dausa</li>
                <li>Davanagere</li>
                <li>Hajipur</li>
            </ul>
        </div>
        <div className="list7">
            <ul style={{listStyle: 'none',color: 'white'}}>
                <li>Pusad</li>
                <li>Adityapur</li>
                <li>Adoni</li>
                <li>Agartala</li>
                <li>Agra</li>
                <li>Ahmedabad</li>
                <li>Ahmednagar</li>
                <li>Aizawl</li>
                <li>Ajmer</li>
                <li>Akola</li>
                <li>Alappuzha</li>
                <li>Aligar</li>
                <li>Alipurduar</li>
                <li>Allahabad</li>
                <li>Almora</li>
                <li>Alwar</li>
                <li>Ambajogai</li>
                <li>Ambala</li>
                <li>Ambikapur</li>
                <li>Ambur</li>
                <li>Amravati</li>
                <li>Amreli</li>
                <li>Amritsar</li>
                <li>Anand</li>
                <li>Anantapur</li>
                <li>Ankleshwar</li>
                <li>Arakkonam</li>
                <li>Arambagh</li>
                <li>Araria</li>
                <li>Arrah</li>
                <li>Asansol</li>
                <li>Aurangabad</li>
                <li>Aurangabadbihar</li>
                <li>Azamgarh</li>
                <li>Baddi</li>
                <li>Bagalkot</li>
                <li>Bagdogra</li>
                <li>Bahadurgarh</li>
                <li>Bahraich</li>
                <li>Balaghat</li>
                <li>Balangir</li>
                <li>Balasore</li>
                <li>Ballari</li>
                <li>Ballia</li>
                <li>Balrampur</li>
                <li>Balurghat</li>
                <li>Banda</li>
                <li>Banglore</li>
                <li>Bankura</li>
                <li>Baramati</li>
                <li>Baran</li>
                <li>Bardhaman</li>
                <li>Bardoli</li>
                <li>Bareliy</li>
                <li>Barh</li>
                <li>Baripada</li>
                <li>Barmer</li>
                <li>Barnala</li>
                <li>Barshi</li>
                <li>Basirhat</li>
                <li>Basti</li>
                <li>Batala</li>
                <li>Bathinda</li>
                <li>Beawar</li>
                <li>Beed</li>
                <li>Begusarai</li>
                <li>Pratapgarh</li>
                <li>Belgaum</li>
                <li>Berhampore</li>
                <li>Berhampur</li>
                <li>Bettiah</li>
                <li>Betul</li>
                <li>Bhadohi</li>
                <li>Bhadrachalam</li>
                <li>Bhadrak</li>
                <li>Bhadravati</li>
                <li>Bhagalpur</li>
                <li>Bhandara</li>
                <li>Bharabanki</li>
                <li>Bharatpur</li>
                <li>Bharuch</li>
                <li>Bhatkal</li>
                <li>Bhavnagar</li>
                <li>Bhawanipatna</li>
                <li>Bhilai</li>
                <li>Bhilwara</li>
                <li>Bhimavaram</li>
                <li>Bhind</li>
                <li>Bhiwadi</li>
                <li>Bhiwani</li>
                <li>Bhopal</li>
                <li>Bhuanewsar</li>
                <li>Bhuj</li>
                <li>Bhusaval</li>
                <li>Bidar</li>
                <li>Biharsarif</li>
                <li>Bijapur</li>
                <li>Bijnor</li>
                <li>Bikaner</li>
                <li>Bilaspur</li>
                <li>Bilimora</li>
                <li>Biswanath-Chariali</li>
                <li>Bodhan-Rural</li>
                <li>Bodinayakanur</li>
                <li>Boisar</li>
                <li>Bokaro</li>
                <li>Bolpur</li>
                <li>Bongaigaon</li>
                <li>Bongaon</li>
                <li>Budaun</li>
                <li>Budhwal</li>
                <li>Bulandshahr</li>
                <li>Buldhan</li>
                <li>Bundi</li>
                <li>Burhanpur</li>
                <li>Buxar</li>
                <li>Central-Goa</li>
                <li>Chaibasa</li>
                <li>Chakdaha</li>
                <li>Chalisgaon</li>
                <li>Chandausi</li>
                <li>Chandigarh</li>
                <li>Chandrapur</li>
                <li>Chennai</li>
                <li>Chhapra</li>
                <li>Chhatarpur</li>
                <li>Chhindwara</li>
                <li>Chidambaram</li>
                <li>Chikhli</li>
                <li>Chikkaballapur</li>
                <li>Chikmanglur</li>
                <li>Chiplun</li>
                <li>Chitradurga</li>
                <li>Chittoor</li>
                <li>Chittorgarh</li>
                <li>Churu</li>
                <li>Coimbator</li>
                <li>Cooch-Behar</li>
                <li>Cuddalore</li>
                <li>Cuttack</li>
                <li>Dahanu</li>
                <li>Dahod</li>
                <li>Daltonganj</li>
                <li>Daman</li>
                <li>Darbhanga</li>
                <li>Darjeeling</li>
                <li>Dasuya</li>
                <li>Dausa</li>
            </ul>
        </div>
        </div>
        <div style={{ borderBottom: '1px solid grey',width:'95vw',marginLeft:'3%',marginTop: '2%',}}>
        </div>
        <div className='lastFoot'>
            <div>
                <img src={swiggyFooter} alt="swiggyFoot-Logo"  className='swiggy-FooterLogo'/>
            </div>
            <div className='copyrightSwiggy'>@ 2023 Swiggy</div>
            <div className='sponsorSWiggy'>
                <img src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_48,h_48/icon-facebook_tfqsuc" alt="" className='spons1'/>
                <img src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_48,h_48/icon-pinterest_kmz2wd" alt="" className='spons2' />
                <img src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_48,h_48/icon-instagram_b7nubh" alt="" className='spons3' />
                <img src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_48,h_48/icon-twitter_gtq8dv" alt="" className='spons4' />
            </div>
        </div>
    </div>
  )
}

export default Footer;